### PR TITLE
Started with the introduction chapter

### PR DESCRIPTION
**Pull request by FreddeFrallan**
Started creating code for the first introduction segments:
    -List Operations
    -Sorting

I´m a bit unsure how to structure the code so that it becomes clear for the students to understand?
Any feedback on this matter is much appreciated.

Merry Xmas

### CODE REVIEW

**Comment by johanmon** [comment]
Hi,
I think we should avoid over use of ++ when one knows what to add to a list. For example:

[element] ++ rest   is better written [element|rest]  since we know that we're adding one element. The ++ operator should only be used when the first argument is variable that is bound to a list of elements at runtime.

**Comment by FreddeFrallan** [comment]
Fair enough, I will revisit the code and make the syntaxical changes.

**Comment by FreddeFrallan** [comment]
Have now updated the code!
Mor information in the commit sections

**Comment by johanmon** [comment]
Updated the code.

The ", do:" syntax only adds to confusion in the beginning so better stick to to the "do .. end" syntax. 

Did some simplifications and to some of the functions.

**Pull request merged**
